Feature/create dashboard
DeFiGeek-Community/megumi-interface pull request #4
Opened 2024-11-17 12:39 UTC by YosukeMiyata

issue #2 ダッシュボードページのUIモック作成

【手を加えた箇所】
・app/componentsフォルダーの中にdashboardフォルダを作成し、コンポーネント関連のファイルは全てここに収納しておきました
・issueに記載されていた/app/components/airdrops/Card.tsxは、chakra UIのCardコンポーネントと名前が被るようでしたので、dashboardフォルダに移して、DashBoardList.tsxと名前を変えさせて頂きました
・takaさんのワイヤフレームに倣いまして、PC版のmaxWidthは1034px、モバイル版は387pxといたしました
・新たに作成したinterfacesフォルダには型をまとめたファイルを配置しております
・ja.jsonとen.jsonの"dashboard"の項目に今回使用した文言はまとめております
　英訳不要とのことでしたので、en.jsonにも日本語の文言を入れております
・pnpm formatのコマンドでprettierを実行できるようにしております

2024-11-18 03:41 UTC, takadr commented
1. ContainerのmaxWidthはChakraで用意されているcontainer.xlを入れておいていただけますか？
モバイルレイアウトは基本幅100%でいいと思うので分岐なしで`maxW={"container.xl"}`でいいと思います

2. レイアウトの変更にisMobileという関数を使ってますが、ウィンドウ幅変更する度に全画面のコンポーネント再描画しているようなので、特に理由がなければCSSで対応できる部分は素直にCSSで対応した方が良さそうと思いました。
（要素数が増えた場合にウィンドウ幅調整すると固まりそう、httpリクエストを誤って大量に発射したりとかありそう）

https://github.com/user-attachments/assets/ceb1fefc-3ff5-436c-b694-74e89ef7df03


例：
```diff
- fontSize={isMobile ? "xl" : "3xl"}
+ fontSize={{ base: "xl", sm: "3xl" }}
```

2024-11-18 11:47 UTC, YosukeMiyata commented
takaさん、コメント誠にありがとうございます！
順次修正して参ります！

> 6. ハイドレーションエラーはテンプレ側の問題なのであとで~v1ブランチに修正コミットしておくので作業ブランチにマージしてください~ → 作業ブランチに直接コミットしたのでpullしてください

6に関しましては、pullした後に、
サーバーサイドレンダリング (SSR) とクライアントサイドレンダリングの間で HTML 属性の不一致が起きている
とのエラーがまだ出ておりましたので、
bodyタグを
<body suppressHydrationWarning={true}>に置き換えて、一旦エラーが出ないようにしております！

2024-11-18 12:02 UTC, YosukeMiyata commented
> 1. ContainerのmaxWidthはChakraで用意されているcontainer.xlを入れておいていただけますか？
>    モバイルレイアウトは基本幅100%でいいと思うので分岐なしで`maxW={"container.xl"}`でいいと思います

ContainerのmaxWidthを、分岐なしの maxW={"container.xl"}に置き換えました！
変更後もレイアウトの崩れはありませんでした！

2024-11-18 12:26 UTC, YosukeMiyata commented
上記の2の項目のtakaさんの動画にございます
UIの全要素をオレンジの四角で囲んだ表示ってどうやって表示されているんでしょうか？
レイアウトの調整がめっちゃ捗りそうと思いました！

2024-11-18 13:28 UTC, YosukeMiyata commented
takaさん、ありがとうございます！
ブラウザのディベロッパーモードを使いこなせるようになりたいなぁ

suppressHydrationWarningは削除いたしました！
コンソールには、以下のエラーが表示されております！

Warning: Extra attributes from the server: class
    at body
    at html
    at RootLayout (Server)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/dev-root-not-found-boundary.js:33:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:321:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/app-router.js:207:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/app-router.js:577:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/app-index.js:112:27)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/app-index.js:117:11)

2024-11-19 01:29 UTC, takadr commented
> Warning: Extra attributes

この警告はAppRouterとChakra uiの相性の問題らしいので、
https://github.com/chakra-ui/chakra-ui/issues/7040#issuecomment-1655818781

SSR時にbodyにclassつけて対応しときました
https://github.com/DeFiGeek-Community/megumi-interface/commit/a74cd028f9815e17b69c1302f4bdfb709e189d17

2024-11-19 12:16 UTC, YosukeMiyata commented
takaさん、ありがとうございます！エラーが出なくなりました！
そういえば、Pages Routerを採用しているpunodwoɔのフロントでは、
chakra UIを使用してもこのようなエラーは出てませんでしたね！
いや〜、こういうエラーを、takaさんやnaizoさんのように、自分で調べて解決できるようになりたいです！
このエラーとwallet connectのRPC関連のエラーと丸一日格闘しましたが、解決に至りませんでした！
自分で対処できないエラーが出てくるのが怖いです！フロント恐怖症w

2024-11-27 11:36 UTC, YosukeMiyata commented
isMobileで画面判定をせずに、CSSで対応した方が良い件につきまして、
RenderCardContent内では、
display={{ base: "none", md: "block" }}のような形で表示、非表示を使い分けてみましたが、
このような使い方ってありでしょうか？？
takaさんが意図されたやり方とは違うような気がしています！
https://github.com/DeFiGeek-Community/megumi-interface/blob/5df93e2f8f4b1d42167b09d3f7895a934795623c/app/components/dashboard/RenderCardContent.tsx#L22
https://github.com/DeFiGeek-Community/megumi-interface/blob/5df93e2f8f4b1d42167b09d3f7895a934795623c/app/components/dashboard/RenderCardContent.tsx#L50

2024-11-27 11:41 UTC, YosukeMiyata commented
takaさん、すみません！
Chromeで見たときに、ダークモードが適用できてないのって、どうにかできましたっけ？？
![image](https://github.com/user-attachments/assets/f374e1b1-5da3-4e4b-b838-e106cdf375de)

2024-11-27 13:52 UTC, takadr commented
> Chromeで見たときに、ダークモード

デフォルトはdarkになってると思うので、localhostでlocal storageに他プロジェクトの設定でlightが入っちゃってたりしますか？
<img width="871" alt="image" src="https://github.com/user-attachments/assets/30b282fa-786e-43e9-84e0-28ea7c5c3af9">

2024-11-27 15:01 UTC, takadr commented
> display={{ base: "none", md: "block" }}のような形で表示、非表示を使い分けてみました

でもいいっちゃいいと思うんですが↓のような感じでBox内の要素のスタイルをbaseとmdで変えるようにしておけばBox全体を2通り書かなくて済むのでbetterだと思います
ステータスのラベルだけ、この構造でスマホ表示で左に寄せたい場合はdisplayで出し分けで対応（か、position: relative + left: -◯◯ とかで調整）できそうです

```js
<Box>
        <RenderDateContent creationDate={creationDate} publicationDate={publicationDate} />
        <Flex
          flexDirection={{ base: "column", md: "row" }}
          justifyContent="center"
          alignItems="center"
          gap="4"
        >
          <Box width={{ base: "full", md: "60%" }}>
            <Row mainAxisAlignment="center" crossAxisAlignment="center" gap="4">
              <Avatar size="lg" name="YMT" bg="gray.500" />
              <Box flex="1">
                <Row
                  mainAxisAlignment="flex-start"
                  crossAxisAlignment="center"
                  gap="2"
                  marginBottom="1"
                >
                  <RenderStatus isResistered={resisteredStatus} />
                </Row>
                <RenderAirdropInfo airdropTitle={airdropTitle} vestingType={vestingType} />
              </Box>
            </Row>
          </Box>
          <Box textAlign="right" width={{ base: "full", md: "40%" }}>
            <RenderDetailedInfo
              totalAmount={totalAmount}
              claimedAccounts={claimedAccounts}
              vestingEndDate={vestingEndDate}
            />
          </Box>
        </Flex>
      </Box>
```

2024-11-28 11:32 UTC, YosukeMiyata commented
> デフォルトはdarkになってると思うので、localhostでlocal storageに他プロジェクトの設定でlightが入っちゃってたりしますか？
chakra ui color modeの項目が light になっておりましたので、直接 dark に書き換えましたところ、
ダークモードで表示することができました！
お手数おかけいたしました！ﾍﾟｺｯ
chrome に dark reader という拡張機能を入れておりますので、その辺りが影響したのかも知れません！
![スクリーンショット 2024-11-28 20 25 45](https://github.com/user-attachments/assets/cd3b0327-418b-4d5b-9dd3-fa5381a846cc)

2024-11-28 23:44 UTC, YosukeMiyata commented
takaさん、コードまでご提示いただきまして誠にありがとうございます！
アドバイスを参考に、ステータスのラベルだけdisplayで出し分けしてみました！

2024-11-29 11:16 UTC, YosukeMiyata commented
components/dashboardディレクトリを削除し、その中に入っていたファイルを、
新たに作成したcomponents/airdrops/card/ディレクトリ以下に配置いたしました！

2024-11-30 09:50 UTC, YosukeMiyata commented
お疲れ様でございます！
issueにございましたダミーデータ型に関しまして、
createdAtの項目にはnumber型しか定義されておりませんでしたが、
undefinedの可能性はないと考えてよろしいでしょうか？
作成日と公開日を表示するロジックをどうしようかと考えておりまして！

2024-11-30 11:04 UTC, takadr commented
はい、airdrop登録時にcreatedAtは必ず登録されるので、undefinedは考慮しなくて大丈夫です

2024-12-01 12:26 UTC, takadr requested changes
5点ほどご確認お願いします

あと、Render〜というコンポーネント名はどこかの命名規則とかですかね？個人的にはコンポーネント名に動詞が入っていると少し違和感を感じるので、もし特に理由なければ RenderDetailedInfo → DetailedInfo のがいいかなと思いました

2024-12-01 12:26 UTC, takadr commented on app/components/airdrops/cards/DashBoardCard.tsx
> +  currentResisteredContractStatus = handleResisteredStatus(airdrop.contractAddress);
```js
currentResisteredAirdropStatus = !!airdrop.merkleTreeUploadedAt;
currentResisteredContractStatus = !!airdrop.contractAddress;
```
でいい気がしますがどうでしょう。
handleResisteredStatusは不要になると思います（この関数はboolean返しているので名前はisResisteredとかの方がよさそう）

2024-12-01 12:26 UTC, takadr commented on app/lib/airdrop/airdropUtils.ts
> +};
実はtempTempleteTypeのhexはテンプレ名をethers.encodeBytes32Stringしたやつだったので、
下記のようにしておいていただけますか？

```js
import { fromHex } from "viem";
export const formatTempleteType = (tempTempleteType: TemplateType) => {
  return fromHex(tempTempleteType, { size: 32, to: "string" });
};
```

TemplateTypeStringとhandleTempleteType（これも命名的にはisStandardとかのがよさそう）が不要になると思います

2024-12-01 12:26 UTC, takadr commented on app/(pages)/dashboard/page.tsx
> +      <DashBoardList />
現状だとdashboard/page.tsxからコンポーネントが無駄に深くネストしてしまってる感じがするので、
DashBoardListとそれに続くRenderAirdropの内容はそのままpage.tsxに書かれてていいと思います。（ダミーデータも）

```js
return (
    <Container maxW={"container.xl"}>
      <Heading fontSize={{ base: "xl", md: "3xl" }}>Dashboard</Heading>
      <Box margin="0 auto" py={{ base: "3", md: "6" }}>
        <Flex justifyContent="space-between" alignItems="center" marginBottom="4">
          ...
        <VStack spacing="4">
          {airdrops.map((airdrop) => <DashBoardCard key={airdrop.id} airdrop={airdrop} />);}
        </VStack>
      </Box>
    </Container>
  );
```
のようなイメージです。

2024-12-01 12:26 UTC, takadr commented on app/components/airdrops/cards/DashBoardCard.tsx
> +        <RenderCardContent {...renderCardProps} />
DashBoardCard内のRenderCardContentも特に別コンポーネントにするメリットなさそうです

2024-12-01 12:26 UTC, takadr commented on app/components/airdrops/cards/RenderDetailedInfo.tsx
> +      </Row>
「べスティング期間終了」の項目はtemplateNameがLinearVestingの場合のみ表示したいです

2024-12-02 11:32 UTC, YosukeMiyata commented
> Render〜というコンポーネント名はどこかの命名規則とかですかね？

ファイル名、コンポーネント名からRender〜を削除いたしました！
今後は付けないようにいたします！

2024-12-02 11:45 UTC, YosukeMiyata commented on app/components/airdrops/cards/DashBoardCard.tsx
> +  currentResisteredContractStatus = handleResisteredStatus(airdrop.contractAddress);
このような書き方があるんですね！

AI君に使い方を尋ねたところ、

二重の否定演算子!!の動作は以下のようになります：

もしairdrop.merkleTreeUploadedAtが:

null: falseになります
undefined: falseになります
0: falseになります
空文字列: falseになります
値が存在する場合（日付や数値など）: trueになります

と教えてもらいました！勉強になりました！

handleResisteredStatusは削除し、変数名はisResistered〜にリネームいたしました！

2024-12-02 22:53 UTC, YosukeMiyata commented on app/lib/airdrop/airdropUtils.ts
> +};
アドバイス通り修正できたかと思います！
真偽値を判定する関数をisStandardとし、返り値を受ける変数名もisStandardといたしましたところ、
怒られましたので、変数名はisStandardTempleteTypeとしました！

2024-12-03 03:42 UTC, takadr commented on app/lib/airdrop/airdropUtils.ts
> +};
`isStandard`（旧`handleTempleteType`）は関数自体削除で、今isStandardで出し分けているのはAirdropInfo.tsxは新しい`formatTemplateType`を使ってこのように対応しておいていただけますか？
テンプレ増えてもなるべく修正箇所少なくて済むようにしておきたいので

```diff
- <Text fontSize={{ base: "sm", sm: "md" }} marginRight="1">
-     {isStandard ? t("dashboard.standard") : t("dashboard.linearVesting")}
- </Text>
+ <Text fontSize={{ base: "sm", sm: "md" }} marginRight="1">
+     {formatTemplateType(templateType)}
+ </Text>
```

2024-12-03 03:44 UTC, takadr commented on app/components/airdrops/cards/CardContent.tsx
> +                  isAirdropResistered={props.isResisteredAirdrop}
全体的にタイポの修正をお願いします
✗ Resister
◯ Register

✗ Templete
◯ Template

2024-12-03 11:34 UTC, YosukeMiyata commented on app/components/airdrops/cards/CardContent.tsx
> +                  isAirdropResistered={props.isResisteredAirdrop}
これは恥ずいw
お手数おかけいたしました！
修正完了いたしました！

2024-12-03 12:07 UTC, YosukeMiyata commented on app/lib/airdrop/airdropUtils.ts
> +};
ご指示の通り、修正いたしました！
{formatTemplateType(templateType)}からの戻り値は、日本語、英語の切り替えに対応しなくて良い感じでしょうか？
以下のように、t( )で囲ってみましたが、切り替えはできませんでした！
https://github.com/DeFiGeek-Community/megumi-interface/blob/9449d5b2ced6564dbe89de8e1b22dc6f916ef0be/app/components/airdrops/cards/AirdropInfo.tsx#L26

2024-12-03 12:30 UTC, YosukeMiyata commented on app/(pages)/dashboard/page.tsx
> +      <DashBoardList />
こちらも修正が完了しました！
コードが冗長になる時に、出来るだけ外部ファイルにコードを切り分けて、
可読性を保つように心がけておりましたが、確かにネストが深くなってしまいますね！
この辺りの匙加減が難しく感じております！
気になる箇所を発見しましたら、またご指摘いただければと存じます！

2024-12-03 12:39 UTC, YosukeMiyata commented on app/components/airdrops/cards/DashBoardCard.tsx
> +        <RenderCardContent {...renderCardProps} />
修正完了いたしました！

2024-12-03 13:03 UTC, YosukeMiyata commented on app/components/airdrops/cards/RenderDetailedInfo.tsx
> +      </Row>
isLinearVestingのフラグを導入して、
要件に合う場合のみ
「べスティング期間終了」と終了年月日を表示するようにいたしました！
![image](https://github.com/user-attachments/assets/d16af1b1-5f33-431c-bc9d-00e4404904e5)

2024-12-04 01:12 UTC, takadr commented on app/lib/airdrop/airdropUtils.ts
> +};
ロケールファイルは用意していただいてるようなので下記でいけると思います

```js
{t(`dashboard.${formatTemplateType(templateType)}`)}
```

2024-12-04 11:26 UTC, YosukeMiyata commented on app/lib/airdrop/airdropUtils.ts
> +};
Takaさん、ありがとうございます！
この書き方をド忘れしておりました！
日本語表記に切り替えることができました！
![image](https://github.com/user-attachments/assets/58e948be-e2d6-4a03-9258-0fda27263795)

2024-12-04 22:46 UTC, takadr approved these changes

2024-12-04 22:47 UTC, takadr commented
ご対応ありがとうございました、こちらで一旦v1ブランチにマージします

2024-12-04 22:51 UTC, merged